apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  # Using mariadb client instead of an init.sql file since we need to run as root to change settings
  # and init.sql invocation happens as the MYSQL_USER
  init.sh: |
    #!/bin/bash
    # postStart runs in parallel with container initialization so need to make sure mariadb is up
    while ! mariadb --user=root --password=admin -e "SELECT 1" &> /dev/null ; do
      echo "MariaDB command not found. Waiting for 3 seconds..."
      sleep 3
    done
    echo "Increasing max connections"
    mariadb --user=root --password=admin -e "SET GLOBAL MAX_CONNECTIONS = 1000;"
    echo "Enabling NO_BACKSLASH_ESCAPES"
    mariadb --user=root --password=admin -e "SET GLOBAL SQL_MODE = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_BACKSLASH_ESCAPES';"
    echo "Creating ranger if not exists"
    mariadb --user=root --password=admin -e "CREATE DATABASE IF NOT EXISTS ranger;"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: maria-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "@PROJECT_ROOT@/mnt/pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: "mariadb/server:11.1.2"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: metastore_db
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mariadb-for-hive
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "2G"
            cpu: 1
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/sh", "-c", "/docker-entrypoint-initdb.d/init.sh" ]
      volumes:
      - name: mariadb-for-hive
        persistentVolumeClaim:
          claimName: maria-pv-claim
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
          defaultMode: 0755
