apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    name: console
  - protocol: TCP
    port: 9000
    targetPort: 9000
    name: service
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        command:
        - /bin/bash
        - -c
        args:
        - minio server /storage --console-address :9090
        env:
        - name: MINIO_ROOT_USER
          value: minio_root_user
        - name: MINIO_ROOT_PASSWORD
          value: minio_root_password123
        volumeMounts:
        - name: storage
          mountPath: /storage
        ports:
        - containerPort: 9090
          name: console
        - containerPort: 9000
          name: service
      volumes:
      - name: storage
        # This volume is based on PVC
        hostPath:
          # Ensure the file directory is created.
          path: /Users/gregfee/code/colossus/mnt/minio-data
          type: DirectoryOrCreate
