apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/User/gregfee/code/colossus/mnt/pg-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ranger-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranger-postgres
spec:
  selector:
    matchLabels:
      app: ranger-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ranger-postgres
    spec:
      containers:
      - name: ranger-postgres
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: ranger-postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "1G"
            cpu: 1
      volumes:
      - name: ranger-postgres-data
        persistentVolumeClaim:
          claimName: pg-pv-claim
