---
apiVersion: v1
kind: Service
metadata:
  name: trino
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: trino-coordinator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator
spec:
  selector:
    matchLabels:
      app: trino-coordinator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trino-coordinator
    spec:
      containers:
      - name: trino
        image: @REPO_NAME@/trino-ranger
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCESS_KEY_ID
          value: minio_root_user
        - name: AWS_SECRET_ACCESS_KEY
          value: minio_root_password123
        volumeMounts:
        - mountPath: /etc/trino
          name: config-volume
        - mountPath: /etc/trino/catalog
          name: catalog-volume
        imagePullPolicy: Never
      volumes:
      - configMap:
          defaultMode: 420
          name: trino-configs-coordinator
        name: config-volume
      - configMap:
          defaultMode: 420
          name: trino-catalogs
        name: catalog-volume
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trino-worker
spec:
  serviceName: trino-worker
  replicas: 1
  selector:
    matchLabels:
      app: trino-worker
  template:
    metadata:
      labels:
        app: trino-worker
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: trino
        image: @REPO_NAME@/trino-ranger
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCESS_KEY_ID
          value: minio_root_user
        - name: AWS_SECRET_ACCESS_KEY
          value: minio_root_password
        volumeMounts:
        - mountPath: /etc/trino
          name: config-volume
        - mountPath: /etc/trino/catalog
          name: catalog-volume
        imagePullPolicy: Never
      volumes:
      - configMap:
          defaultMode: 420
          name: trino-configs-worker
        name: config-volume
      - configMap:
          defaultMode: 420
          name: trino-catalogs
        name: catalog-volume
