---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: trino-configs-coordinator
data:
  jvm.config: |-
    -server
    -Xmx16G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Djdk.attach.allowAttachSelf=true
    -XX:-UseBiasedLocking
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.nio.maxCachedBufferSize=2000000
    -XX:+UnlockDiagnosticVMOptions
    -XX:+UseAESCTRIntrinsics 
  node.properties: |-
    node.environment=production
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin
  config.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    query.max-memory=200GB
    query.max-memory-per-node=8GB
    query.max-stage-count=200
    task.writer-count=4
    discovery.uri=http://trino:8080
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: trino-configs-worker
data:
  jvm.config: |-
    -server
    -Xmx16G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Djdk.attach.allowAttachSelf=true
    -XX:-UseBiasedLocking
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.nio.maxCachedBufferSize=2000000
    -XX:+UnlockDiagnosticVMOptions
    -XX:+UseAESCTRIntrinsics
  node.properties: |-
    node.environment=production
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin
  config.properties: |-
    coordinator=false
    http-server.http.port=8080
    query.max-memory=200GB
    query.max-memory-per-node=10GB
    query.max-stage-count=200
    task.writer-count=4  
    discovery.uri=http://trino:8080
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: trino-catalogs
data:    
  hive.properties: |-
    connector.name=hive
    hive.metastore.uri=thrift://hive-metastore:9083
    hive.allow-drop-table=true
    hive.s3.endpoint=http://minio:9000
    hive.s3.aws-access-key=minio_root_user
    hive.s3.aws-secret-key=minio_root_password123
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
    hive.s3.max-connections=100
  iceberg.properties: |-
    connector.name=iceberg
    hive.metastore.uri=thrift://hive-metastore:9083
    hive.s3.endpoint=http://minio:9000
    hive.s3.aws-access-key=minio_root_user
    hive.s3.aws-secret-key=minio_root_password123
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
    hive.s3.max-connections=100
  delta.properties: |-
    connector.name=delta_lake
    delta.enable-non-concurrent-writes=true
    hive.metastore.uri=thrift://hive-metastore:9083
    hive.s3.endpoint=http://minio:9000
    hive.s3.aws-access-key=minio_root_user
    hive.s3.aws-secret-key=minio_root_password123
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
    hive.s3.max-connections=100    
  mysql.properties: |-
    connector.name=mysql
    connection-url=jdbc:mysql://mariadb:3306
    connection-user=admin
    connection-password=admin
